/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CommanderRouteImport } from './routes/commander'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffRestaurantRouteImport } from './routes/staff/restaurant'
import { Route as StaffManagerRouteImport } from './routes/staff/manager'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as MaCommandeTokenRouteImport } from './routes/ma-commande.$token'

const CommanderRoute = CommanderRouteImport.update({
  id: '/commander',
  path: '/commander',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRestaurantRoute = StaffRestaurantRouteImport.update({
  id: '/staff/restaurant',
  path: '/staff/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffManagerRoute = StaffManagerRouteImport.update({
  id: '/staff/manager',
  path: '/staff/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaCommandeTokenRoute = MaCommandeTokenRouteImport.update({
  id: '/ma-commande/$token',
  path: '/ma-commande/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commander': typeof CommanderRoute
  '/ma-commande/$token': typeof MaCommandeTokenRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/manager': typeof StaffManagerRoute
  '/staff/restaurant': typeof StaffRestaurantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commander': typeof CommanderRoute
  '/ma-commande/$token': typeof MaCommandeTokenRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/manager': typeof StaffManagerRoute
  '/staff/restaurant': typeof StaffRestaurantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commander': typeof CommanderRoute
  '/ma-commande/$token': typeof MaCommandeTokenRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/manager': typeof StaffManagerRoute
  '/staff/restaurant': typeof StaffRestaurantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commander'
    | '/ma-commande/$token'
    | '/staff/login'
    | '/staff/manager'
    | '/staff/restaurant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commander'
    | '/ma-commande/$token'
    | '/staff/login'
    | '/staff/manager'
    | '/staff/restaurant'
  id:
    | '__root__'
    | '/'
    | '/commander'
    | '/ma-commande/$token'
    | '/staff/login'
    | '/staff/manager'
    | '/staff/restaurant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommanderRoute: typeof CommanderRoute
  MaCommandeTokenRoute: typeof MaCommandeTokenRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffManagerRoute: typeof StaffManagerRoute
  StaffRestaurantRoute: typeof StaffRestaurantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/commander': {
      id: '/commander'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/restaurant': {
      id: '/staff/restaurant'
      path: '/staff/restaurant'
      fullPath: '/staff/restaurant'
      preLoaderRoute: typeof StaffRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/manager': {
      id: '/staff/manager'
      path: '/staff/manager'
      fullPath: '/staff/manager'
      preLoaderRoute: typeof StaffManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ma-commande/$token': {
      id: '/ma-commande/$token'
      path: '/ma-commande/$token'
      fullPath: '/ma-commande/$token'
      preLoaderRoute: typeof MaCommandeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommanderRoute: CommanderRoute,
  MaCommandeTokenRoute: MaCommandeTokenRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffManagerRoute: StaffManagerRoute,
  StaffRestaurantRoute: StaffRestaurantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
